# Basic Site Settings
locale: "en-US"
title: "RR."
title_separator: "-"
name: "Rezaur Rashid"
description: # "Causal AI | XAI | Graph Neural Networks | AI in Healthcare | Cancer Research"
nav:
  - title: "About"
    url: /about/
  - title: "Research"
    url: /research/
  - title: "CV"
    url: /cv/
  - title: "Publications"
    url: /publications/
url: "https://rezaurrashid.github.io"
baseurl: ""
repository: "rashid-mdrezaur/rezaurrashid.github.io"

# Author Sidebar Info
author:
  avatar: "picture/profile.jpg" # update to your photo's filename, e.g. "profile.jpg"
  name: "Rezaur Rashid, PhD"
  pronouns: "he/him/his"
  bio: "Postdoctoral Research Fellow, UTHSC"
  location: "Memphis, TN, USA"
  employer: "UT Health Science Center"
  email: "mrashid7@uthsc.edu"
  googlescholar: "https://scholar.google.com/citations?user=1ys5rQYAAAAJ&hl=en"
  orcid: "http://orcid.org/0000-0003-1343-5364"
  linkedin: "rezaurrashid"
  # github: "rezaurrashid"
  # Add more if desired, or leave blank

# Publication Category for grouping
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'
  conferences:
    title: 'Conference Papers (Peer-Reviewed)'
  others:
    title: 'Abstracts and Workshops (Peer-Reviewed)'

# Only keep these includes for your main pages and files
include:
  - _pages
  - files

# Default settings for pages
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown settings
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# These settings control the types of collections used by the template
collections:
  publications:
    output: true
    permalink: /:collection/:path/


# These settings control how pages and collections are included in the site
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true


# Plugins (safe list for GitHub Pages)
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-redirect-from
  - jemoji


# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: Etc/UTC # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

