# Basic Site Settings
locale: "en-US"
title: "Rezaur Rashid, PhD"
title_separator: "-"
name: "Rezaur Rashid"
description: "Causal AI | XAI | Graph Neural Networks | AI in Healthcare | Cancer Research"
nav:
  - title: "About"
    url: /about/
  - title: "Research"
    url: /research/
  - title: "CV"
    url: /cv/
  - title: "Publications"
    url: /publications/
url: "https://rezaurrashid.github.io"
baseurl: ""
repository: "rashid-mdrezaur/rezaurrashid.github.io"

# Author Sidebar Info
author:
  avatar: "profile.png" # update to your photo's filename, e.g. "profile.jpg"
  name: "Rezaur Rashid"
  pronouns: "he/him/his"
  bio: "Postdoctoral Scholar, UTHSC"
  location: "Memphis, TN, USA"
  employer: "The University of Tennessee Health Science Center"
  email: "mrashid7@uthsc.edu"
  googlescholar: "https://scholar.google.com/citations?user=1ys5rQYAAAAJ&hl=en"
  orcid: "http://orcid.org/0000-0003-1343-5364"
  linkedin: "rezaurrashid"
  github: "rashid-mdrezaur"
  # Add more if desired, or leave blank

# Publication Category for grouping
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'
  conferences:
    title: 'Conference Papers (Peer-Reviewed)'
  other:
    title: 'Confernce Abstracts and Workshops (Peer-Reviewed)'

# Only keep these includes for your main pages and files
include:
  - _pages
  - files

# Default settings for pages
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Conversion and Markdown settings
markdown: kramdown
highlighter: rouge

# Plugins (safe list for GitHub Pages)
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Timezone
timezone: Etc/UTC
